### ISSUE TITLE
Null PlayerInfoCapability in UpdatePlayerInfoPacket

### ISSUE THREAD

**Issue by greysondn** [Cibernet83/SplatCraft#11]
It just keeps appearing in the logs.

```
[11Dec2022 21:50:06.481] [Render thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Client
java.lang.NullPointerException: null
	at net.splatcraft.forge.data.capabilities.playerinfo.PlayerInfoCapability.get(PlayerInfoCapability.java:30) ~[splatcraft:3.0.0-1.16.5]
	at net.splatcraft.forge.network.s2c.UpdatePlayerInfoPacket.execute(UpdatePlayerInfoPacket.java:47) ~[splatcraft:3.0.0-1.16.5]
	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:201) ~[forge:?]
	at net.splatcraft.forge.network.s2c.PlayToClientPacket.consume(PlayToClientPacket.java:16) ~[splatcraft:3.0.0-1.16.5]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:114) ~[forge:?]
	at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:114) ~[forge:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:148) ~[forge:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:66) ~[forge:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:72) ~[forge:?]
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:77) ~[forge:?]
	at java.util.Optional.map(Optional.java:265) ~[?:?]
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:77) ~[forge:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147240_a(ClientPlayNetHandler.java:1905) ~[?:?]
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:59) ~[?:?]
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:11) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:948) ~[?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) ~[minecraft-1.16.5-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) ~[forge-1.16.5-36.2.39-launcher.jar:36.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57) [ForgeWrapper-mmc2.jar:mmc2]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175) [NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185) [NewLaunch.jar:?]
	at org.polymc.EntryPoint.listen(EntryPoint.java:144) [NewLaunch.jar:?]
	at org.polymc.EntryPoint.main(EntryPoint.java:74) [NewLaunch.jar:?]
```

**Comment by Octol1ttle** [comment]
Can you provide steps to reproduce this issue?

**Comment by greysondn** [comment]
I've asked the same player that provided the above logs to step in here and do a minimal reproduction case. It may take some time, but I'll try to stay on them about it.

**Comment by greysondn** [comment]
We are as of yet unable to reproduce this. It is suspected that it was caused by the Mohist server software.

Please standby; I intend to try testing this under an ordinary forge server tonight to see if we can reproduce it there.

If it turns out that it was Mohist, I will update with a comment essentially asking for close-won't-fix; Mohist openly admits that they cause incompatibilities and are willing to work on it themselves as far as I've ever understood. But as of right now, we don't plan to run under Mohist anyway :)

-----------------------------------------------------------------

We have just had this occur once in a plain, jane Forge server.

We are still trying to get lucky enough to catch the cause.

@gamefreq0 is assisting me with this, and was the source of the original report's log.

**Comment by greysondn** [comment]
```
Data Packs: vanilla, mod:borderlesswindow (incompatible), mod:startupqol (incompatible), mod:notes (incompatible), mod:notenoughcrashes, mod:fast_projectile_fix, mod:creeperfix (incompatible), mod:flatbedrock (incompatible), mod:jei, mod:suggestionproviderfix, mod:mmoparties (incompatible), mod:rsgauges, mod:noautojump (incompatible), mod:taxfreelevels (incompatible), mod:xaeroworldmap, mod:progressive_aggressivity, mod:controlling, mod:configured, mod:powah, mod:ascpm, mod:greysondn_command_wands, mod:nomadictents, mod:bookshelf, mod:craftdumper (incompatible), mod:potionstacker, mod:ichunutil, mod:crafttweaker, mod:paraglider, mod:forge, mod:chalk, mod:exp_bottling, mod:sounddeviceoptions (incompatible), mod:dimensionteleport, mod:fxcontrol (incompatible), mod:parkour_recorder (incompatible), mod:ping, mod:betterdrowning (incompatible), mod:jade, mod:lollipop, mod:towers_of_the_wild, mod:smoothboot, mod:jeiintegration, mod:flywheel, mod:create, mod:curios, mod:patchouli (incompatible), mod:xaerominimap, mod:betterbiomeblend, mod:autoreglib (incompatible), mod:quark (incompatible), mod:securitycraft, mod:fluxnetworks, mod:doubleslabs, mod:xercapaint (incompatible), mod:hardcorerevival (incompatible), mod:tombstone, mod:obfuscate, mod:clef, mod:lootr (incompatible), mod:computercraft, mod:nbtperipheral, mod:ears, mod:switchbow, mod:fastleafdecay, mod:controllable (incompatible), mod:codechickenlib (incompatible), mod:cb_multipart (incompatible), mod:projectred-core (incompatible), mod:projectred-illumination (incompatible), mod:projectred-transmission (incompatible), mod:projectred-exploration (incompatible), mod:projectred-integration (incompatible), mod:prettybeaches (incompatible), mod:chiselsandbits (incompatible), mod:morphtool (incompatible), mod:bettermodsbutton, mod:threadsafety, mod:openloader, mod:createaddition, mod:betteradvancements, mod:cloth-config (incompatible), mod:dsurround, mod:supermartijn642configlib, mod:cookingforblockheads (incompatible), mod:supermartijn642corelib, mod:wormhole, mod:geckolib3 (incompatible), mod:doom (incompatible), mod:bountifulbaubles (incompatible), mod:farmingforblockheads (incompatible), mod:mcjtylib, mod:capsule, mod:emendatusenigmatica, file/GDN-v5, mod:worldedit (incompatible), mod:areas, mod:you_cant_see_me, mod:gdn_placeholders, mod:placebo (incompatible), mod:biomeidfixer, mod:craftvania2, mod:mcwbridges, mod:botania, mod:ominousdarkness, mod:collective, mod:appliedenergistics2 (incompatible), mod:nobreeding (incompatible), mod:antiportals, mod:chickenchunks (incompatible), mod:dimpaintings, mod:randompatches, mod:zawa, mod:refinedpipes, mod:phantomconfig, mod:incontrol (incompatible), mod:multimine, mod:leap (incompatible), mod:vehicle (incompatible), mod:architectury, mod:lightoverlay (incompatible), mod:forgeautofish (incompatible), mod:scannable (incompatible), mod:beefix, mod:jeitweaker, mod:projecte, mod:chococraft, mod:movingelevators, mod:createtweaker, mod:actuallycompatible, mod:steampowered, mod:parcool (incompatible), mod:appliedenergisticstweaker, mod:step (incompatible), mod:sophisticatedbackpacks, mod:dynview (incompatible), mod:snailmail, mod:aiimprovements, mod:fastsuite (incompatible), mod:artifacts, mod:farsight_view, mod:fastbench (incompatible), mod:performant (incompatible), mod:fastfurnace (incompatible), mod:ferritecore (incompatible), mod:expandability, mod:ctm (incompatible), mod:splatcraft (incompatible)
```

edit: more readable version
```
Data Packs: vanilla
mod:borderlesswindow (incompatible)
mod:startupqol (incompatible)
mod:notes (incompatible)
mod:notenoughcrashes
mod:fast_projectile_fix
mod:creeperfix (incompatible)
mod:flatbedrock (incompatible)
mod:jei
mod:suggestionproviderfix
mod:mmoparties (incompatible)
mod:rsgauges
mod:noautojump (incompatible)
mod:taxfreelevels (incompatible)
mod:xaeroworldmap
mod:progressive_aggressivity
mod:controlling
mod:configured
mod:powah
mod:ascpm
mod:greysondn_command_wands
mod:nomadictents
mod:bookshelf
mod:craftdumper (incompatible)
mod:potionstacker
mod:ichunutil
mod:crafttweaker
mod:paraglider
mod:forge
mod:chalk
mod:exp_bottling
mod:sounddeviceoptions (incompatible)
mod:dimensionteleport
mod:fxcontrol (incompatible)
mod:parkour_recorder (incompatible)
mod:ping
mod:betterdrowning (incompatible)
mod:jade
mod:lollipop
mod:towers_of_the_wild
mod:smoothboot
mod:jeiintegration
mod:flywheel
mod:create
mod:curios
mod:patchouli (incompatible)
mod:xaerominimap
mod:betterbiomeblend
mod:autoreglib (incompatible)
mod:quark (incompatible)
mod:securitycraft
mod:fluxnetworks
mod:doubleslabs
mod:xercapaint (incompatible)
mod:hardcorerevival (incompatible)
mod:tombstone
mod:obfuscate
mod:clef
mod:lootr (incompatible)
mod:computercraft
mod:nbtperipheral
mod:ears
mod:switchbow
mod:fastleafdecay
mod:controllable (incompatible)
mod:codechickenlib (incompatible)
mod:cb_multipart (incompatible)
mod:projectred-core (incompatible)
mod:projectred-illumination (incompatible)
mod:projectred-transmission (incompatible)
mod:projectred-exploration (incompatible)
mod:projectred-integration (incompatible)
mod:prettybeaches (incompatible)
mod:chiselsandbits (incompatible)
mod:morphtool (incompatible)
mod:bettermodsbutton
mod:threadsafety
mod:openloader
mod:createaddition
mod:betteradvancements
mod:cloth-config (incompatible)
mod:dsurround
mod:supermartijn642configlib
mod:cookingforblockheads (incompatible)
mod:supermartijn642corelib
mod:wormhole
mod:geckolib3 (incompatible)
mod:doom (incompatible)
mod:bountifulbaubles (incompatible)
mod:farmingforblockheads (incompatible)
mod:mcjtylib
mod:capsule
mod:emendatusenigmatica
file/GDN-v5
mod:worldedit (incompatible)
mod:areas
mod:you_cant_see_me
mod:gdn_placeholders
mod:placebo (incompatible)
mod:biomeidfixer
mod:craftvania2
mod:mcwbridges
mod:botania
mod:ominousdarkness
mod:collective
mod:appliedenergistics2 (incompatible)
mod:nobreeding (incompatible)
mod:antiportals
mod:chickenchunks (incompatible)
mod:dimpaintings
mod:randompatches
mod:zawa
mod:refinedpipes
mod:phantomconfig
mod:incontrol (incompatible)
mod:multimine
mod:leap (incompatible)
mod:vehicle (incompatible)
mod:architectury
mod:lightoverlay (incompatible)
mod:forgeautofish (incompatible)
mod:scannable (incompatible)
mod:beefix
mod:jeitweaker
mod:projecte
mod:chococraft
mod:movingelevators
mod:createtweaker
mod:actuallycompatible
mod:steampowered
mod:parcool (incompatible)
mod:appliedenergisticstweaker
mod:step (incompatible)
mod:sophisticatedbackpacks
mod:dynview (incompatible)
mod:snailmail
mod:aiimprovements
mod:fastsuite (incompatible)
mod:artifacts
mod:farsight_view
mod:fastbench (incompatible)
mod:performant (incompatible)
mod:fastfurnace (incompatible)
mod:ferritecore (incompatible)
mod:expandability
mod:ctm (incompatible)
mod:splatcraft (incompatible)
```

GDN Placeholders is a small mcreator mod that just adds a few items to use as placeholder macguffin objects (to target for replacement in data/res packs via predicate matching). It is unlikely to be the cause.

Edit: greysondn_command_wands similarly adds a single wand to use as the worldedit wand. Again, small MCreator mod; again, unlikely to be the cause.

The rest should be publicly available.

**Comment by Octol1ttle** [comment]
I'm very certain that this is not a mod compatibility issue but rather a bug within Splatcraft

**Comment by greysondn** [comment]
If there's anything we can do to help from our modpack dev server, as non-java people, please feel free to let me know.

I'm at a loss. We can't get it to reproduce on demand. It just seems to happen.

---

Quoting @gamefreq0 here:

> Looks like leaving and rejoining the server gave the Splatcraft NPE
>
> But not every time
>
> In fact, it only happened once, at a quarter to 3 last night
>
> Pops up right after Xaero's minimap updates, so I have an idea on what to test next time; I'll leave and rejoin with you nearby, close enough to show up on my minimap when I load in

So it appears that the one half consistent time it happens is during server login. I'm not going to point fingers at Xaero's, but of course we're going to try it later on.

**Comment by Octol1ttle** [comment]
More insight has been found on this issue. Notably, the issue occurs because *the entity holding* the PlayerInfoCapability is `null`, not the PIC itself. It appears the NPE is thrown when a player gets outside the client's render distance (and outside the client world) by the time the packet is delivered. The client world plays an important role in this because the entity is retrieved from it. (`PlayerEntity target = Minecraft.getInstance().level.getPlayerByUUID(this.target);`)
Exception stacktrace:
```
[13Mar2023 23:42:09.440] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] Chichi16 was splatted by Octol1ttle using [Grim Blaster]
[13Mar2023 23:42:14.837] [Render thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Client
java.lang.NullPointerException: Cannot invoke "net.minecraft.entity.LivingEntity.getCapability(net.minecraftforge.common.capabilities.Capability)" because "entity" is null
	at net.splatcraft.forge.data.capabilities.playerinfo.PlayerInfoCapability.get(PlayerInfoCapability.java:30) ~[splatcraft:3.1.0-111466e-1.16.5]
	at net.splatcraft.forge.network.s2c.UpdatePlayerInfoPacket.execute(UpdatePlayerInfoPacket.java:47) ~[splatcraft:3.1.0-111466e-1.16.5]
	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:201) ~[forge:?]
	at net.splatcraft.forge.network.s2c.PlayToClientPacket.consume(PlayToClientPacket.java:16) ~[splatcraft:3.1.0-111466e-1.16.5]
```
(5 second gap is the respawn timer).
